# -*- coding: utf-8 -*-
"""admincambios_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TOvFpF6IN0yYvx8C73o2M0J8R8NILZzM
"""

import streamlit as st
import datetime
import os
import pandas as pd

# ==========================================
# 1. CONFIGURACIÓN DE PÁGINA Y ESTILOS (UI)
# ==========================================
st.set_page_config(
    page_title="Control de Disponibilidad - Change Management",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Inyección de CSS limpio para mejorar la estética de la app
st.markdown("""
    <style>
    .block-container { padding-top: 2rem; padding-bottom: 2rem; }
    .stMetric { background-color: #f8f9fa; padding: 15px; border-radius: 10px; border-left: 5px solid #0066cc; }
    div[data-testid="stMetricValue"] { font-size: 24px !important; font-weight: bold; }

    /* ============================
       Sidebar compacto (login)
       ============================ */
    /* Reduce padding general del sidebar */
    div[data-testid="stSidebar"] .css-1d391kg { padding: 8px 12px; }

    /* Etiquetas y textos más pequeños en sidebar */
    div[data-testid="stSidebar"] label,
    div[data-testid="stSidebar"] .stTextInput,
    div[data-testid="stSidebar"] .stSelectbox,
    div[data-testid="stSidebar"] .stRadio {
        font-size: 13px !important;
    }

    /* Inputs y selects más compactos */
    div[data-testid="stSidebar"] input[type="text"],
    div[data-testid="stSidebar"] input[type="password"],
    div[data-testid="stSidebar"] .stDateInput input {
        font-size: 13px !important;
        padding: 6px 8px !important;
        height: 30px !important;
    }

    /* Botones más pequeños en sidebar */
    div[data-testid="stSidebar"] button {
        padding: 6px 10px !important;
        font-size: 13px !important;
    }

    /* Ajuste del header del sidebar */
    div[data-testid="stSidebar"] h2, div[data-testid="stSidebar"] h3 {
        font-size: 14px !important;
        margin-bottom: 6px !important;
    }

    /* Evitar que el sidebar ocupe demasiado ancho en pantallas pequeñas */
    @media (max-width: 900px) {
        div[data-testid="stSidebar"] { width: 220px !important; }
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 2. CONSTANTES Y CONFIGURACIÓN INICIAL
# ==========================================
USUARIOS_INICIALES = [
    "Juan Camilo Ríos Rentería",
    "Meredys Mercado Muentes",
    "Brahian Andrés López Echeverri",
    "Andrés Felipe Jaramillo Malambo",
    "Jessica Alexandra Flórez Montoya",
    "Juan Felipe Sierra Tobón",
    "Andrés Mauricio Vargas Osorio",
    "Cristian David Requeme Gallego"
]

FECHA_INICIO = datetime.date(2026, 8, 21)

VIERNES_FESTIVOS = {
    datetime.date(2026, 4, 3),   # Viernes Santo
    datetime.date(2026, 5, 1),   # Día del Trabajo
    datetime.date(2026, 7, 7),   # Festivo específico
    datetime.date(2026, 12, 25), # Navidad
    datetime.date(2027, 1, 1),   # Año Nuevo
}

CSV_FILE = "novedades_auditoria.csv"
PASSWORD_ADMIN = "AdminChange2026"  # <-- Tu contraseña de administrador

# ==========================================
# 3. SISTEMA DE ARCHIVOS Y AUDITORÍA
# ==========================================
def cargar_novedades_desde_csv():
    if not os.path.exists(CSV_FILE):
        df = pd.DataFrame(columns=["ID_Novedad", "Empleado", "Fecha_Inicio", "Fecha_Fin", "Creado_Por", "Fecha_Hora_Registro"])
        df.to_csv(CSV_FILE, index=False, encoding='utf-8')
        return {}

    try:
        df = pd.read_csv(CSV_FILE, encoding='utf-8')
        diccionario_novedades = {}
        for _, row in df.iterrows():
            f_ini = datetime.datetime.strptime(str(row["Fecha_Inicio"]), "%Y-%m-%d").date()
            f_fin = datetime.datetime.strptime(str(row["Fecha_Fin"]), "%Y-%m-%d").date()
            diccionario_novedades[row["Empleado"]] = (f_ini, f_fin)
        return diccionario_novedades
    except:
        return {}

def registrar_novedad_en_csv(empleado, f_inicio, f_fin, administrador):
    df = pd.read_csv(CSV_FILE, encoding='utf-8') if os.path.exists(CSV_FILE) else pd.DataFrame()

    # Calcular un ID único incremental
    nuevo_id = int(df["ID_Novedad"].max() + 1) if not df.empty else 1
    ahora = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    nueva_fila = {
        "ID_Novedad": nuevo_id,
        "Empleado": empleado,
        "Fecha_Inicio": f_inicio.strftime("%Y-%m-%d"),
        "Fecha_Fin": f_fin.strftime("%Y-%m-%d"),
        "Creado_Por": administrador,
        "Fecha_Hora_Registro": ahora
    }

    df = pd.concat([df, pd.DataFrame([nueva_fila])], ignore_index=True)
    df.to_csv(CSV_FILE, index=False, encoding='utf-8')

def eliminar_novedad_por_id(id_eliminar):
    if os.path.exists(CSV_FILE):
        df = pd.read_csv(CSV_FILE, encoding='utf-8')
        # Filtrar el DataFrame dejando fuera el ID seleccionado
        df = df[df["ID_Novedad"] != int(id_eliminar)]
        df.to_csv(CSV_FILE, index=False, encoding='utf-8')

# Inicializar novedades del disco duro
SITUACIONES_ESPECIALES = cargar_novedades_desde_csv()

# ==========================================
# 4. MOTOR LÓGICO DE CÁLCULO
# ==========================================
def generar_calendario_equitativo(semanas_a_calcular=20):
    calendario = []
    cola_deudas = []
    idx_ruleta = 0
    viernes_actual = FECHA_INICIO

    for _ in range(semanas_a_calcular):
        if viernes_actual in VIERNES_FESTIVOS:
            calendario.append({
                "Fecha": viernes_actual.strftime('%d/%m/%Y'),
                "Semana": viernes_actual.isocalendar()[1],
                "Usuario": "FESTIVO (Sin disponibilidad)",
                "Detalle": "No laborable"
            })
            viernes_actual += datetime.timedelta(weeks=1)
            continue

        usuario_asignado = None
        motivo_asignacion = "Turno Normal"

        def esta_libre(nombre, fecha):
            if nombre in SITUACIONES_ESPECIALES:
                inicio, fin = SITUACIONES_ESPECIALES[nombre]
                if inicio <= fecha <= fin:
                    return False
            return True

        for u in list(cola_deudas):
            if esta_libre(u, viernes_actual):
                usuario_asignado = u
                cola_deudas.remove(u)
                motivo_asignacion = "Compensación de turno pendiente"
                break

        if usuario_asignado is None:
            while True:
                candidato = USUARIOS_INICIALES[idx_ruleta]
                idx_ruleta = (idx_ruleta + 1) % len(USUARIOS_INICIALES)

                if esta_libre(candidato, viernes_actual):
                    usuario_asignado = candidato
                    break
                else:
                    if candidato not in cola_deudas:
                        cola_deudas.append(candidato)

        calendario.append({
            "Fecha": viernes_actual.strftime('%d/%m/%Y'),
            "Semana": viernes_actual.isocalendar()[1],
            "Usuario": usuario_asignado,
            "Detalle": motivo_asignacion
        })
        viernes_actual += datetime.timedelta(weeks=1)

    return calendario

# ==========================================
# 5. DISEÑO DE LA INTERFAZ GRÁFICA (UI)
# ==========================================
st.title("🔮 Control de Disponibilidad Inteligente de Administración de Cambios")
st.markdown("Plataforma oficial para la planeación equitativa de turnos y control de novedades de ingeniería.")
st.markdown("---")

# Manejo de la sesión de autenticación interna de Streamlit
if "usuario_logueado" not in st.session_state:
    st.session_state["usuario_logueado"] = None

# --- BARRA LATERAL: CONTROL DE ACCESO ---
st.sidebar.header("🔒 Control de Acceso")

if st.session_state["usuario_logueado"] is None:
    # Formulario de Login si nadie está conectado
    rol_seleccionado = st.sidebar.radio("Selecciona tu rol:", ["Espectador", "Administrador"])

    if rol_seleccionado == "Administrador":
        password_ingresado = st.sidebar.text_input("Contraseña de Admin:", type="password")
        nombre_admin = st.sidebar.text_input("Tu Nombre/Usuario:", value="Admin_User")

        if st.sidebar.button("Iniciar Sesión"):
            if password_ingresado == PASSWORD_ADMIN and nombre_admin.strip() != "":
                st.session_state["usuario_logueado"] = nombre_admin
                st.success("Sesión iniciada correctamente.")
                st.rerun()
            else:
                st.sidebar.error("Contraseña incorrecta o usuario vacío")
else:
    # Vista si ya estás logueada
    st.sidebar.success(f"👤 Conectada como: {st.session_state['usuario_logueado']}")

    # NUEVO: Botón de cierre de sesión explícito
    if st.sidebar.button("⚠️ Cerrar Sesión", type="primary"):
        st.session_state["usuario_logueado"] = None
        st.success("Sesión cerrada.")
        st.rerun()

# Formulario de Registro de Novedades (Solo si la sesión está activa)
if st.session_state["usuario_logueado"] is not None:
    st.sidebar.markdown("---")
    st.sidebar.header("📝 Registrar Novedad")
    usuario_sel = st.sidebar.selectbox("Compañero:", USUARIOS_INICIALES)
    fecha_inicio_sel = st.sidebar.date_input("Fecha Inicio Novedad:", datetime.date(2026, 8, 21))
    fecha_fin_sel = st.sidebar.date_input("Fecha Fin Novedad:", datetime.date(2026, 8, 21))

    if st.sidebar.button("💾 Guardar en Registro"):
        if fecha_inicio_sel <= fecha_fin_sel:
            registrar_novedad_en_csv(usuario_sel, fecha_inicio_sel, fecha_fin_sel, st.session_state["usuario_logueado"])
            st.sidebar.success(f"¡Registro guardado!")
            st.rerun()
        else:
            st.sidebar.error("Error: La fecha de inicio no puede ser mayor a la de fin.")

# --- ÁREA PRINCIPAL CON DISEÑO DE PESTAÑAS ---
tab_proyeccion, tab_auditoria = st.tabs(["📅 Proyección de Calendario", "Bitácora de Auditorías"])

with tab_proyeccion:
    semanas = st.slider("Ajustar horizonte de simulación (Semanas):", min_value=4, max_value=52, value=20)

    datos_calendario = generar_calendario_equitativo(semanas)
    turnos_reales = [r for r in datos_calendario if "FESTIVO" not in r["Usuario"]]

    st.write("#### 🎯 Próximos Turnos Críticos")
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric(label="🟢 ESTA SEMANA", value=turnos_reales[0]["Usuario"], delta=f"Viernes {turnos_reales[0]['Fecha']}")
    with col2:
        st.metric(label="🔵 PRÓXIMA SEMANA", value=turnos_reales[1]["Usuario"], delta=f"Viernes {turnos_reales[1]['Fecha']}")
    with col3:
        st.metric(label="🟡 SIGUIENTE SEMANA", value=turnos_reales[2]["Usuario"], delta=f"Viernes {turnos_reales[2]['Fecha']}")

    st.markdown(" ")
    st.write("#### 📊 Calendario de Disponibilidad Proyectado")
    st.dataframe(datos_calendario, use_container_width=True)

with tab_auditoria:
    st.write("#### 🕵️‍♂️ Historial del Sistema")
    st.markdown("Registro oficial de transacciones físicas de novedades.")

    # Cargar y leer el archivo CSV en tiempo real
    if os.path.exists(CSV_FILE) and os.path.getsize(CSV_FILE) > 10:
        df_logs = pd.read_csv(CSV_FILE, encoding='utf-8')

        # --- NUEVA FUNCIÓN: ACCIONES DE ELIMINACIÓN ---
        if st.session_state["usuario_logueado"] is not None:
            st.markdown("---")
            st.write("⚙️ **Panel de Modificaciones de Auditoría**")
            col_sel, col_btn = st.columns([3, 1])

            with col_sel:
                # Permite al admin elegir un ID de novedad registrado para borrarlo
                id_para_borrar = st.selectbox("Selecciona el ID de la novedad que deseas eliminar o corregir:", df_logs["ID_Novedad"].tolist())
            with col_btn:
                st.write(" ") # Espacio estético
                if st.button("❌ Eliminar Registro", type="secondary", use_container_width=True):
                    eliminar_novedad_por_id(id_para_borrar)
                    st.success(f"Novedad #{id_para_borrar} eliminada con éxito.")
                    st.rerun()
            st.markdown("---")

        # Mostrar los logs con lo más nuevo arriba
        st.dataframe(df_logs.iloc[::-1], use_container_width=True)
    else:
        st.info("No hay novedades registradas físicamente en el sistema en este momento.")